language: rust
sudo: false
cache: cargo
rust:
  - stable
notifications:
  slack:
    secure: h4NGLrnMWSgDdJMYtWKmCFT7RMdsm8n4cXjeQytjMBHLVCQnfk8DPr4NcBpZqwhaME1+JJkYp5lCTFrv0fwDOgRNwQqgJCOmLzdxYFsrl+Hp0jLC1Ll3NQDs1EmDG3+9kPP5UTw8wNK+BkM9/rSb3VOHiXooptT5olzq76LIjdJLhT17iD+5q8KZtt57TEMCz8UdF9I5ogeg+gJVTVS9t7QeIqnKu9h3vb7CoHajNa/7kyw2opOEIo6wXF3KWWXj9M5K1QXOUDk4D72zIRO/FQib9wU+4AyrWb+c6ADcwtP5EBVlIlleEvRfAT4PJX8mc74hz49teNgmlV39wH1LPo+sQ7rL6Kfg5NpqIOlRSdZVuCFqaCQVFqbYgCjcjTvmy2aFTFLdA0mYUhXoCQjR/5QeJImm0JM/Ai+49cZ/Asc4JP3rQmDt6oh1vhHLETjOl9Xx8HpbhIXdMsmL1scHySCMau4almv8UisDFbohA+zJ9nsGq7N606jyyVgZwke4zemsrPhtgoxHcKT7w/VTRUIRjQk+iq8GYkfiLNqhB2iIDr7ZwPsbVRGtt1f9G/gL5Jo4SvskOP2Pqp+jDwDU7C/zTpDNhD95JgvTcQn/wtJQq4KC+NMEkWeyhvF1k5reyxw6+INb0MjwkNn6/dgNTEXQlSmes3mrysfFphrspNM=
