[workspace]
members = [".", "velox", "velox-server"]

[package]
name = "velox-core"
version = "0.1.0-wip"
authors = ["LFalch <lucas@wasd.dk>"]

[dependencies]
simple-vector2d = {version = "0.1", features = ["serde-serial"]}
serde = "0.9"
serde_derive = "0.9"
rand = "0.3"
bincode = "=1.0.0-alpha6"
